# Action to build openwrt images
---
name: build rpm

on:
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build-mockbuilder:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: mockbuilder:latest
          outputs: type=docker,dest=/tmp/mockbuilder.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mockbuilder
          path: /tmp/mockbuilder.tar    

  build-rpm:
    runs-on: ubuntu-24.04
    needs: build-mockbuilder

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: mockbuilder
          path: /tmp

      - name: Load image
        run: |
          podman load --input /tmp/mockbuilder.tar

      - name: Build image
        run: |
          ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rpm
          path: build_dir
